### ISSUE TITLE
--colorenhance problem

### ISSUE THREAD

**Issue by t0ffi** [jhgjeraker/rnc-color-stretch#3]
Hi,
Thank for for converting this script to python.

I have one issue, when tried to set --colorenhance parameter it only accepts integer. When set for example 1.2 I received: 

> main.py: error: argument --colorenhance: invalid int value: '1.2'

Maybe was doing something wrongly.

**Comment by t0ffi** [comment]
Changed --colorenhance to float and now it is working

**Comment by jhgjeraker** [comment]
I just checked the original Davinci script and you are correct, `colorenhance` should be a float, not int. Good catch. I'll fix this.
